# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'CycleCash' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CycleCash

  target 'CycleCashTests' do
    # Pods for testing
  end

  target 'CycleCashUITests' do
    # Pods for testing
  end

end
